# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-01 14:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ssh_qa', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Frontdb',
        ),
    ]
