# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-01 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ssh_qa', '0002_delete_frontdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Frontdb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': '\u524d\u7aef\u9879\u76ee',
                'verbose_name_plural': '\u524d\u7aef\u9879\u76ee',
            },
        ),
    ]
