# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-09 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile_api',
            name='api_device',
            field=models.IntegerField(choices=[(0, '\u82f9\u679c'), (1, '\u5b89\u5353'), (2, '\u5176\u4ed6')]),
        ),
        migrations.AlterField(
            model_name='mobile_api',
            name='api_version',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
